// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNOZKQQYO5Xs6uK3ZuATQYSrf95WUn8xs',
    appId: '1:387197450939:web:3638d4a8c98de1cf59879e',
    messagingSenderId: '387197450939',
    projectId: 'madauth-3dd1a',
    authDomain: 'madauth-3dd1a.firebaseapp.com',
    storageBucket: 'madauth-3dd1a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4q3H5BOnyfgzi0Js8hZqoI-6bbBLF3gE',
    appId: '1:387197450939:android:fa7bb32ec5c4c5d059879e',
    messagingSenderId: '387197450939',
    projectId: 'madauth-3dd1a',
    storageBucket: 'madauth-3dd1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc2RW0_OY6BhXI85MEG87oL71VQe6VZRM',
    appId: '1:387197450939:ios:17831467d33aeca459879e',
    messagingSenderId: '387197450939',
    projectId: 'madauth-3dd1a',
    storageBucket: 'madauth-3dd1a.appspot.com',
    iosBundleId: 'com.example.leafHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc2RW0_OY6BhXI85MEG87oL71VQe6VZRM',
    appId: '1:387197450939:ios:4af5db65398b17c559879e',
    messagingSenderId: '387197450939',
    projectId: 'madauth-3dd1a',
    storageBucket: 'madauth-3dd1a.appspot.com',
    iosBundleId: 'com.example.leafHub.RunnerTests',
  );
}
